### ISSUE TITLE
Floor Reader Transparency

### ISSUE THREAD

**Issue by Suharpy** [Solybum/PSOBBMod-Addons#22]
Would it be possible to make the floor reader transparent, similar to the Monster Reader?  Would be excellent.

**Comment by Solybum** [comment]
I see...
I will be updating my addons soon to remove the theme related code. (it will be a global theme managed by the framework itself).

I will try to add this change with that.... maybe if I get some time tomorrow.

**Comment by Suharpy** [comment]
thanks, i love your work <3

**Comment by Solybum** [comment]
https://github.com/Solybum/PSOBBMod-Addons/commit/776ec22c1b39609e1d6ea68a38d28776441b47ea adds TransparentWindow options to the floor reader windows.

**Comment by Suharpy** [comment]
thanks so much :)
