### ISSUE TITLE
This invulnerability option does not save upon restarting the game or reloading addons

### ISSUE THREAD

**Issue by Firkraag8** [Solybum/PSOBBMod-Addons#26]
https://github.com/Solybum/PSOBBMod-Addons/blob/82a96264159430ab06e8a0e261d0fe9204e7c1be/Player%20Reader/init.lua#L155

**Comment by Solybum** [comment]
Thank you.
It was fixed here https://github.com/Solybum/PSOBBMod-Addons/pull/25
