### ISSUE TITLE
Branch push permission

### ISSUE THREAD

**Issue by GilPalma** [Solybum/PSOBBMod-Addons#7]
I know this isn't the place to post this in but I cloned this repository, made a new local branch with some changes but am not allowed to push it. I thought this was fully open to contribute. Can't even find an email to contact.

Is it not possible to push a branch here? Can I get some permissions?

It'd be great if you could review my changes and see if you'd like them added to the master branch.

**Comment by GilPalma** [comment]
Found you on the forums. I'm going to close this pseudo issue.

**Comment by Solybum** [comment]
As I replied in the forum, you have to clone your fork instead of my repo, then issue pull requests whenever you have something you think is worth adding.
