### ISSUE TITLE
Timer - Countdown - Hotkey: Crashing without options.lua

### ISSUE THREAD

**Issue by SandroSpengler** [Solybum/PSOBBMod-Addons#78]
Hello,

i've noticed that opening the Timer -> Counterdown -> Hotkeys dropdown causes the timer plugin to crash if no options.lua file exists.

![TimerCountdownCrashAction](https://github.com/Solybum/PSOBBMod-Addons/assets/67550509/3a855b52-43c9-4f88-9b09-ec486ae8701e)

Clicking the dropdown results in the following errorlog.

![TimerCountdownCrashLog](https://github.com/Solybum/PSOBBMod-Addons/assets/67550509/ee414355-510d-4d13-a8a8-4eeb06cd0b7d)

**Comment by Solybum** [comment]
Thanks for the report, fixed it.
